app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: if-else-test
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1729742041196-source-1729742087262-target
      source: '1729742041196'
      sourceHandle: source
      target: '1729742087262'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: end
      id: 1729742087262-true-1729742113480-target
      source: '1729742087262'
      sourceHandle: 'true'
      target: '1729742113480'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: end
      id: 1729742087262-f133a298-5d41-441c-b5c1-a3a8ae088b0f-17297421203950-target
      source: '1729742087262'
      sourceHandle: f133a298-5d41-441c-b5c1-a3a8ae088b0f
      target: '17297421203950'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: end
      id: 1729742087262-false-17297421257720-target
      source: '1729742087262'
      sourceHandle: 'false'
      target: '17297421257720'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: text
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: text
      height: 90
      id: '1729742041196'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: contains
            id: 359e46f1-d15a-4cc8-ab19-5ed29f148cb6
            value: '1'
            varType: string
            variable_selector:
            - '1729742041196'
            - text
          id: 'true'
          logical_operator: and
        - case_id: f133a298-5d41-441c-b5c1-a3a8ae088b0f
          conditions:
          - comparison_operator: contains
            id: 47cdbcc0-0e25-40fd-a39f-203d1388b1d2
            value: '2'
            varType: string
            variable_selector:
            - '1729742041196'
            - text
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支
        type: if-else
      height: 174
      id: '1729742087262'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1729742041196'
          - text
          variable: text1
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1729742113480'
      position:
        x: 723
        y: 145
      positionAbsolute:
        x: 723
        y: 145
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1729742041196'
          - text
          variable: text2
        selected: false
        title: 结束 (1)
        type: end
      height: 90
      id: '17297421203950'
      position:
        x: 723
        y: 318
      positionAbsolute:
        x: 723
        y: 318
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1729742041196'
          - text
          variable: text3
        selected: false
        title: 结束 (2)
        type: end
      height: 90
      id: '17297421257720'
      position:
        x: 723
        y: 494
      positionAbsolute:
        x: 723
        y: 494
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -327.5
      y: -42
      zoom: 1