# LLM配置文件
llm:
  deepseek:
    sk: ${llm.deepseek.sk:-YOUR_DEEPSEEK_API_KEY}
    enabled: false
    models:
      - name: deepseek-chat
        enabled: true
        default: true
  tongyi:
    sk: ${llm.tongyi.sk:-YOUR_TONGYI_API_KEY}
    enabled: false
    models:
      - name: qwen-max
        enabled: true
        default: true
  openrouter:
    sk: ${llm.openrouter.sk:-YOUR_OPENROUTER_API_KEY}
    enabled: false
    models:
      - name: google/gemini-2.5-pro
        enabled: true
        default: true
  ollama:
    sk: ${llm.ollama.sk:ollama-local}
    enabled: false
    base-url: ${llm.ollama.base_url:http://localhost:11434}
    models:
      - name: qwen:7b
        enabled: true
        default: true

# Web搜索配置 - 支持多种搜索引擎，按优先级自动选择
web-search:
  # Bocha AI搜索服务 - 高质量AI总结，支持日期过滤
  bocha:
    sk: ${web-search.bocha.sk:-YOUR_BOCHA_API_KEY}
    enabled: true  # 启用博查搜索，提供最佳搜索体验
  
  # DuckDuckGo搜索服务 - 免费即时答案，无需API密钥
  duckduckgo:
    enabled: false  # 作为备选方案，当Bocha不可用时启用
  
  # SerpAPI搜索服务 - Google搜索结果，免费层每月100次
  serpapi:
    api_key: ${web-search.serpapi.api_key:-YOUR_SERPAPI_API_KEY}
    enabled: false  # 需要API密钥
  
  # SearchAPI.io搜索服务 - 多搜索引擎支持，免费层每月100次
  searchapi:
    api_key: ${web-search.searchapi.api_key:-YOUR_SEARCHAPI_API_KEY}
    enabled: false  # 需要API密钥
  
  # 已废弃的配置（保留以兼容旧版本）
  bing:
    sk: ${web-search.bing.sk:-YOUR_BING_API_KEY}
    enabled: false

# 金融工具配置
finance:
  alpha-vantage:
    api-key: ${finance.alpha-vantage.api-key:-YOUR_ALPHA_VANTAGE_API_KEY}
    enabled: false
  finnhub:
    api-key: ${finance.finnhub.api-key:-YOUR_FINNHUB_API_KEY}
    enabled: false
  yahoo-finance:
    enabled: true

web:
  port: 8999
  host: 0.0.0.0
  workers: 8

# 向量存储配置
vector:
  local:
    enabled: true
    dimension: 384
    index_name: "default"

# 嵌入模型配置
embedding:
  local:
    enabled: true
    model_name: "all-MiniLM-L6-v2"
    dimension: 384
    use_mirror: true
    mirror_url: "https://hf-mirror.com" 